// Code generated by "stringer -type=CodeChangeReason -trimprefix=CodeChange -output gen_code_change_reason_stringer.go"; DO NOT EDIT.

package tracing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeChangeUnspecified-0]
	_ = x[CodeChangeContractCreation-1]
	_ = x[CodeChangeGenesis-2]
	_ = x[CodeChangeAuthorization-3]
	_ = x[CodeChangeAuthorizationClear-4]
	_ = x[CodeChangeSelfDestruct-5]
	_ = x[CodeChangeRevert-6]
	_ = x[CodeChangeSystemContractUpgrade-192]
}

const (
	_CodeChangeReason_name_0 = "UnspecifiedContractCreationGenesisAuthorizationAuthorizationClearSelfDestructRevert"
	_CodeChangeReason_name_1 = "SystemContractUpgrade"
)

var (
	_CodeChangeReason_index_0 = [...]uint8{0, 11, 27, 34, 47, 65, 77, 83}
)

func (i CodeChangeReason) String() string {
	switch {
	case i <= 6:
		return _CodeChangeReason_name_0[_CodeChangeReason_index_0[i]:_CodeChangeReason_index_0[i+1]]
	case i == 192:
		return _CodeChangeReason_name_1
	default:
		return "CodeChangeReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
