name: Build Go for all platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
    
      - name: Build
        run: make geth
    
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-cross-artifacts
          path: build/bin/geth